version: '3.1'

services:
  profiler-database:
    container_name: "profiler-database"
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 6Z9JrWN44Q63
      MYSQL_DATABASE: profiler-db
      TZ: Europe/Berlin
    volumes:
      - profiler_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  profiler_data:
